# Generated by Django 5.0.1 on 2024-11-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handicraft', '0003_hero_alter_productcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(upload_to='hero/'),
        ),
    ]
