# Generated by Django 5.0.1 on 2024-11-10 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Handicraft', '0004_alter_hero_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
