# Generated by Django 5.0.1 on 2024-12-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handicraft', '0005_delete_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Ganesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Sarsoti_Laxmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Tara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Utencils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Product_Buddha',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
