# Generated by Django 5.1.4 on 2024-12-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handicraft', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='history',
            field=models.TextField(default='History not available'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
