# Generated by Django 5.1.4 on 2024-12-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handicraft', '0009_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_buddha',
            name='category',
            field=models.CharField(default='buddha', max_length=100),
        ),
        migrations.AddField(
            model_name='product_ganesh',
            name='category',
            field=models.CharField(default='ganesh', max_length=100),
        ),
        migrations.AddField(
            model_name='product_sarsoti_laxmi',
            name='category',
            field=models.CharField(default='sarsoti_laxmi', max_length=100),
        ),
        migrations.AddField(
            model_name='product_tara',
            name='category',
            field=models.CharField(default='tara', max_length=100),
        ),
        migrations.AddField(
            model_name='utencils',
            name='category',
            field=models.CharField(default='utencils', max_length=100),
        ),
    ]
